deployments:
  environmentMapping:
    Production:
      - "production"
      - "production*"
      - "Production"
      - "PRODUCTION"

  deploymentGating:
    enabled: true # to enable the feature
    retry: 50 # run poll action 50 times
    sleep: 30 # wait 30 seconds between each poll
    environments: # select the environments you'd like to use with this feature
    - Production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2JlM2ExZTVjLTA4NTYtNGE1MS1iZDAyLWI0ZjMzOGRiOTkwMy83MzNlMzUwMC1hMTk1LTExZWYtYTRiMS0xMjAxZjE2ZWQ0MWY=
